name = "Redis"
uuid = "56cc56ef-33c0-4257-b87b-d162a881a166"
authors = ["Deniz Kırlıdoğ <deniz.kirlidog@matriksdata.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
